Feat/ios/staylist search field
codesquad-member-2020/airbnb-03 pull request #22
Opened 2020-05-20 15:04 UTC by kjoonk

검색 필드 뷰와 검색 필터 뷰 작업이에요.
각 클래스에 주석으로 간단히 설명 넣었어요.

## 일반
ViewFromXib라는 프로토콜이 있는데, VC에서 nib 로드할 때 처리하려고 만들어 봤어요.

## 검색 필드
텍스트 필드 델리게이트는 별도 클래스로 뺐는데, 뷰 안에서 델리게이트 지정하는 게 어색하긴 하네요.

## 검색 필터
필터 버튼에 대한 상위클래스를 두었고, 각 버튼마다 상속 받게 했어요.

2020-05-20 16:59 UTC, corykim0829 requested changes
수고하셨습니다!

2020-05-20 16:59 UTC, corykim0829 commented on iOS/AirbnbApp/AirbnbApp/StayList/StayListViewController.swift
> +    private func viewFromXib<T>(_ type: T.Type) -> T where T: ViewFromXib {
이 부분을 프로토콜에 넣을 수 있지 않을까요?

2020-05-20 16:59 UTC, corykim0829 commented on iOS/AirbnbApp/AirbnbApp/StayList/StayListViewController.swift
> +            fatalError("Failed to load from xib: \(T.self)")
뷰 수준에서 fatalError가 나면 안될 것 같아요. 어차피 뷰 수준에서 error가 난다는건 실행조차 안되는 것 같아서, fatalError보다는 다른 방식으로 처리를 하는게 좋을 것 같아요!

2020-05-20 16:59 UTC, corykim0829 commented on iOS/AirbnbApp/AirbnbApp/StayList/Views/SearchFieldView.swift
> +}
프로토콜로 한 부분이 좋네요! 👍

2020-05-20 16:59 UTC, corykim0829 commented on iOS/AirbnbApp/AirbnbApp/StayList/Views/SearchFieldView.swift
> +    static let xibName = String(describing: SearchFieldView.self)
nib과 xib 차이가 뭔지 알아보는 것도 좋을 것 같아요. 저도 잘 몰라서 ㅎ

2020-05-20 16:59 UTC, corykim0829 commented on iOS/AirbnbApp/AirbnbApp/StayList/Views/SearchFieldView.swift
> +    private let searchTextFieldDelegate = SearchTextFieldDelegate()
TextFeildDelegate는 ViewController가 갖는게 더 좋지 않을까요?

2020-05-20 16:59 UTC, corykim0829 commented on iOS/AirbnbApp/AirbnbApp/StayList/Views/SearchFieldView.swift
> +class SearchTextFieldDelegate: NSObject, UITextFieldDelegate {
클래스는 하나의 파일로 분리 컨벤션!

2020-05-20 19:04 UTC, corykim0829 requested changes

2020-05-20 19:04 UTC, corykim0829 commented on iOS/AirbnbApp/AirbnbApp/StayList/StayListViewController.swift
> +    private var filterView: SearchFilterView!
클래스명과 변수명은 통일하면 좋을 것 같아요!

2020-05-20 19:05 UTC, corykim0829 commented
뷰 부분은 스크린샷까지 같이 첨부하면 좋을 것 같아요!!

2020-05-21 02:11 UTC, kjoonk commented on iOS/AirbnbApp/AirbnbApp/StayList/StayListViewController.swift
> +    private func viewFromXib<T>(_ type: T.Type) -> T where T: ViewFromXib {
프로토콜에 넣는다면 static method 형태가 될 텐데, 흠 생각해봐야겠어요.

2020-05-21 02:12 UTC, kjoonk commented on iOS/AirbnbApp/AirbnbApp/StayList/StayListViewController.swift
> +    private var filterView: SearchFilterView!
그러게요. 바꿔야겠어요.

2020-05-21 02:13 UTC, kjoonk commented on iOS/AirbnbApp/AirbnbApp/StayList/Views/SearchFieldView.swift
> +class SearchTextFieldDelegate: NSObject, UITextFieldDelegate {
👌

2020-05-21 02:22 UTC, kjoonk commented
![Simulator Screen Shot - iPhone 11 - 2020-05-21 at 11 21 47](https://user-images.githubusercontent.com/50904665/82516308-5d6a6280-9b55-11ea-978e-c04174529e2b.png)

2020-05-21 02:29 UTC, corykim0829 commented on iOS/AirbnbApp/AirbnbApp/StayList/StayListViewController.swift
> +    private func viewFromXib<T>(_ type: T.Type) -> T where T: ViewFromXib {
static으로 안해도 할 수 있을 것 같아요! 이따가 같이 이야기 해봐요

2020-05-21 02:30 UTC, kjoonk commented on iOS/AirbnbApp/AirbnbApp/StayList/StayListViewController.swift
> +            fatalError("Failed to load from xib: \(T.self)")
근데, 어차피 로드가 되지 않으면 error가 나는 상황이라 더 구체적으로 알 수 있다는 점이 있을 것 같아요.

2020-05-21 02:32 UTC, kjoonk commented on iOS/AirbnbApp/AirbnbApp/StayList/Views/SearchFieldView.swift
> +    static let xibName = String(describing: SearchFieldView.self)
nib은 바이너리 형태이고, xib는 xml 기반이라고 하네요. 애플 문서에도 둘을 혼용해서 쓰고 있고, 주로 nib이라고 하긴 해요. xib라고 이름 지은 건, 기존 UIKit의 nib관련 메소드와 헷갈리지 않으려고 한 거에요. 😃

2020-05-21 02:34 UTC, kjoonk commented on iOS/AirbnbApp/AirbnbApp/StayList/Views/SearchFieldView.swift
> +    private let searchTextFieldDelegate = SearchTextFieldDelegate()
그러게요. outlet으로 잡으면 되겠네요.
번외로, 생성시점 때문에 didSet을 사용했는데, 다른 방법이 있을 지 모르겠어요.

2020-05-21 02:38 UTC, kjoonk commented on iOS/AirbnbApp/AirbnbApp/StayList/Views/SearchFieldView.swift
> +class SearchTextFieldDelegate: NSObject, UITextFieldDelegate {
iOS/AirbnbApp/AirbnbApp/StayList/Views/FilterButton.swift(파일 링크 어떻게 걸죠??) 의 하위 클래스처럼 선언만 한 경우에는 상황에 따라 분리하는 게 나아 보여요.

2020-05-21 02:39 UTC, kjoonk commented on iOS/AirbnbApp/AirbnbApp/StayList/Views/SearchFieldView.swift
> +}
😃

2020-05-21 02:45 UTC, corykim0829 commented on iOS/AirbnbApp/AirbnbApp/StayList/Views/SearchFieldView.swift
> +    private let searchTextFieldDelegate = SearchTextFieldDelegate()
viewDidAppear에서 delegate를 지정해주면 될 것 같아요

2020-05-21 02:47 UTC, corykim0829 commented on iOS/AirbnbApp/AirbnbApp/StayList/StayListViewController.swift
> +            fatalError("Failed to load from xib: \(T.self)")
뷰 자체가 로드가 안되면, 실행에 의미가 없다고 생각되서 당연히 오류없이 로드 되어야한다는 느낌이 들어요 저는 그래서 error 처리가 필요없도록? 해야할 것 같아요

2020-05-21 06:32 UTC, corykim0829 approved these changes
수고하셨습니다!

2020-05-21 06:33 UTC, merged