StayDetailView 기본 동작 구현
codesquad-member-2020/airbnb-03 pull request #54
Opened 2020-05-26 06:39 UTC by kjoonk

상세 뷰에 대한 기본 구현이에요.
- TabBarController > NavigationController > StayListViewController 구조로 바꿨어요.
- Cell 터치 시 상세뷰로 이동: collectionView의 delegate를 썼는데, 셀 크기가 작아지는 문제가 있네요. 같이 해결해보거나, 다른 방법을 써야 할 것 같아요.
- DetailSectionView: 상세 뷰를 이런 식으로 나누면 될 것 같아요. 테스트용으로 label, button만 두었어요.
- RoundedBorder: 공통 스타일을 이런 식으로 적용하면 어떨까 싶어요. 프로토콜이랑 익스텐션 써서요. 기본값을 어떻게 처리할까가 고민이긴 한데, 메소드의 인자로 우선 구현했어요. 다른 방법으로는 상속받아서 사용하는 방법이 있겠고요. 
- DetailButton: RoundedBorder를 적용한 예시에요. DetailSectionView 안에 있는 버튼이에요.

2020-05-26 07:06 UTC, corykim0829 requested changes
수고하셨습니다!

2020-05-26 07:06 UTC, corykim0829 commented on iOS/AirbnbApp/AirbnbApp/StayList/Controllers/StayListViewController.swift
> +        stayListCollectionView.delegate = stayListCollectionViewDelegate
이 부분은 stayListCollectionView 클래스 파일에 가면, 제가 그 안에서 delegate를 지정해놨는데, 여기서 delegate를 변경해서 그럴거에요.

2020-05-26 07:06 UTC, corykim0829 commented on iOS/AirbnbApp/AirbnbApp/TabBar/TabBarController.swift
> +    private var navViewController: UINavigationController!
큰 차이는 없지만 stayListViewController를 내부 프로퍼티로 살리는건 어떨까요?

2020-05-26 12:52 UTC, kjoonk commented on iOS/AirbnbApp/AirbnbApp/StayList/Controllers/StayListViewController.swift
> +        stayListCollectionView.delegate = stayListCollectionViewDelegate
음.. `UICollectionView`와 `UICollectionViewFlowLayout` 두 개가 `delegate`를 같이 써서 생기는 문제였네요. 
두 delegate 구현부를 하나의 클래스로 옮겼더니 잘 작동해요.

2020-05-26 12:57 UTC, kjoonk commented on iOS/AirbnbApp/AirbnbApp/TabBar/TabBarController.swift
> +    private var navViewController: UINavigationController!
`TabBarController`의 속성으로 살리자는 건가요? 지워도 괜찮길래 지웠어요. 나중에 `stayListViewController`를 직접 제어할 일이 있으면 그때 살려도 되지 않을까 싶어요.

2020-05-26 13:21 UTC, kjoonk commented on iOS/AirbnbApp/AirbnbApp/TabBar/TabBarController.swift
> +    private var navViewController: UINavigationController!
`navViewController` 속성도 지워버렸어요. 어차피 `viewControllers` 속성으로 가지고 있어서요.

2020-05-27 07:33 UTC, corykim0829 approved these changes
수고하셨습니다!!

2020-05-27 07:33 UTC, merged