StayCell TapGestureRecognizer 구현
codesquad-member-2020/airbnb-03 pull request #69
Opened 2020-05-27 11:36 UTC by corykim0829

## TapGestureRecognizer
UITapGestureRecognizer을 사용하여 스크롤 뷰 위에도 tap을 처리할 수 있도록 구현하였습니다.
받은 tap의 location의 포인트를 계산하여 해당 cell의 indexPath를 계산 하였습니다.

## CollectionViewTapDelegate
StayListCollectionViewTapDelegate 프로토콜을 만들어서 StayListVC가 채택하여 CollectionView의 action을 위임하여 처리할 수 있도록 구현하였습니다.
tap selector에서 indexPath와 함께 tapDelegate의 didTapCell() 메소드에 전달하도록 하였습니다.

## DataSource의 id 가져오기
StayListVC에서 DataSource의 id를 알기 위해서 DataSource에 클로저를 사용하여 handler parameter를 통해서 id를 전달하도록 구현하였습니다.

## 리팩토링
StayList 관련 final class로 변경해주었고, 코드 위치를 extension과 MARK로 정리하였습니다.

2020-05-27 13:04 UTC, kjoonk requested changes
github으로 소스 보기가 익숙칠 않네요..
고생하셨어요!

2020-05-27 13:04 UTC, kjoonk commented on iOS/AirbnbApp/AirbnbApp/StayList/Views/StayListCollectionView.swift
>          super.init(frame: frame, collectionViewLayout: UICollectionViewFlowLayout())
`layout` 인자를 사용하지 않고 있네요. 옵셔널이나 기본값을 주는 것으로 바꾸는 게 어때요?

2020-05-27 13:04 UTC, kjoonk commented on iOS/AirbnbApp/AirbnbApp/StayList/Views/StayListCollectionView.swift
> +        tapDelegate?.didTapCell(at: indexPath)
와.. 이런 기능이 있는 줄 몰랐어요! 좌표로 indexPath를 알 수 있다니. 😲

2020-05-27 13:04 UTC, kjoonk commented on iOS/AirbnbApp/AirbnbApp/StayList/Controllers/StayListViewController.swift
>          stayListCollectionView.delegate = stayListCollectionViewDelegate
configure...() 메소드가 다음 줄과 잘 이어지지 않아서요.
윗 두 줄을 메소드가 객체를 반환하게 하여 self의 속성에 넣는 걸로 바꾸면 어떨까요?

2020-05-27 13:04 UTC, kjoonk commented on iOS/AirbnbApp/AirbnbApp/StayList/Controllers/StayListViewController.swift
> +}
이렇게 따로 빼니 더 낫네요!

2020-05-27 13:04 UTC, kjoonk commented on iOS/AirbnbApp/AirbnbApp/StayList/ViewModels/StayListCollectionViewDataSource.swift
> +    func idForCell(at indexPath: IndexPath, handler: (Int) -> Void) {
메소드명이 좀 모호해보여요. idForCell만 보면 id를 반환할 것 같아서요. 근데 또 뒤에 handler가 있으니 괜찮은 것 같기도 하고..
음.. 저도 적절한 단어는 떠오르질 않네요. 🤔

2020-05-27 13:18 UTC, corykim0829 commented on iOS/AirbnbApp/AirbnbApp/StayList/ViewModels/StayListCollectionViewDataSource.swift
> +    func idForCell(at indexPath: IndexPath, handler: (Int) -> Void) {
맞아요.. 저도 나름 고민해봤는데 더 적절한게 떠오르지는 않더라구요 ㅋㅋ

2020-05-27 13:18 UTC, corykim0829 commented on iOS/AirbnbApp/AirbnbApp/StayList/Views/StayListCollectionView.swift
> +        tapDelegate?.didTapCell(at: indexPath)
저도 구글링해서 찾았어요 신기방기

2020-05-27 13:18 UTC, corykim0829 commented on iOS/AirbnbApp/AirbnbApp/StayList/Controllers/StayListViewController.swift
>          stayListCollectionView.delegate = stayListCollectionViewDelegate
위에 optional로 private 프로퍼티로 모두 선언해 놓아서 이런 방식이 좋을 것 같아서 이렇게 했어요 메소드가 객체를 반환하게 하면 뷰컨트롤러가 delegate, datasource를 계속해서 가지고 있을 수 없을 것 같아서요

2020-05-27 13:18 UTC, corykim0829 commented on iOS/AirbnbApp/AirbnbApp/StayList/Views/StayListCollectionView.swift
>          super.init(frame: frame, collectionViewLayout: UICollectionViewFlowLayout())
한번 해볼게요!

2020-05-28 05:59 UTC, corykim0829 commented on iOS/AirbnbApp/AirbnbApp/StayList/Views/StayListCollectionView.swift
>          super.init(frame: frame, collectionViewLayout: UICollectionViewFlowLayout())
layout 인자를 사용하면, 에러가 뜨네요. 
현재 초기화 할 때 인자를 사용하지 않아서 바로 super.init이 호출 될거에요.

2020-05-28 06:08 UTC, kjoonk approved these changes

2020-05-28 06:09 UTC, merged